[env:esp32-poe-iso]
platform = espressif32 @ ^6.9.0
board = esp32-poe-iso
framework = arduino
monitor_speed = 115200
lib_deps =
    mathieucarbou/ESPAsyncWebServer @ ^3.6.0
    mathieucarbou/AsyncTCP @ ^3.3.2
    robtillaart/INA226 @ ^0.6.0
    bblanchon/ArduinoJson @ ^7.0.4
